Controllers/assignQuestionToTestController.cs
using NMDCATEtestPreparatory.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Web.Script.Serialization;
using Newtonsoft.Json;

namespace NMDCATEtestPreparatory.Controllers
{
    public class assignQuestionToTestController : Controller
    {
        private nMDCATPrepTestEntities db = new nMDCATPrepTestEntities();
        private nmdcatGeneral ng = new nmdcatGeneral();
        [Authorize(Roles = "UserR,User")]
        [HttpPost]
        public ActionResult loadQuestion(long qClass, int chapter, int sSubject, int testId)
        {
            List<long> testQuestionIds = new List<long>();


            var data = (from q in db.testQuestionDatabanks
                        where q.chapter == chapter && q.questionClassId == qClass && q.subjectId == sSubject
                        select new
                        {
                            Questionid = q.questionId,
                            QuestionTitle = q.questionTitle,
                            choiceA = q.choiceA,
                            choiceB = q.choiceB,
                            choiceC = q.choiceC,
                            choiceD = q.choiceD,
                            dup=db.testQuestions.Where(x=>x.questionId==q.questionId && x.testId==testId).Count()


                        }).ToList();
            foreach (var question in data)
            {
                testQuestionIds.Add(question.Questionid);
            }

            return Json(data, JsonRequestBehavior.AllowGet);

        }

        // GET: assignQuestionToTest
        [Authorize(Roles = "UserR,User")]
        [HttpGet]

        public ActionResult Index()
        {
            ViewBag.questionClass = ng.getStudentClass();
            ViewBag.sSubject = ng.getSubjects();
            ViewBag.ttest = ng.getActivetest();
            return View();
        }
        [Authorize(Roles = "UserR,User")]
        [HttpPost]
   public ActionResult Index(string selectedQuestions, int? studentId, long[] qid, int[] qmarks, string ttest, string questionClass, string sSubject)
        {
            //QuestionId Marks
            string jsonString = selectedQuestions;

            // Deserialize the JSON string into a list of QuestionModel objects
            List<SelectedQuestionData> questionList = JsonConvert.DeserializeObject<List<SelectedQuestionData>>(jsonString);

            //var a = selectedQuestions[0].QuestionId;
            long subjectId = Convert.ToInt64(sSubject);
            long questionClassId = Convert.ToInt64(questionClass);
            long testId = Convert.ToInt64(ttest);
            //    long chapter = Convert.ToInt64(chapter);

            foreach (var item in questionList)
            {
                testQuestion newQuestion = new testQuestion();
                newQuestion.questionId = item.QuestionId;
                newQuestion.marks = item.Marks;
                newQuestion.testId = testId;


                db.testQuestions.Add(newQuestion);
                db.SaveChanges();
            }

            //List<int> fairquestionmarks = new List<int>();
            //for (var j = 0; j < qmarks.Length; j++)
            //{
            //    if (qmarks[j] != 0)
            //    {
            //        fairquestionmarks.Add(qmarks[j]);
            //    }
            //}

            //var duplicateQuestions = new List<string>();
            //for (var i = 0; i < qid.Length; i++)
            //{
            //    long currentQuestionId = qid[i];
            //    bool questionExistsInTest = db.testQuestions.Any(tq => tq.testId == testId && tq.questionId == currentQuestionId);

            //    if (!questionExistsInTest)
            //    {
            //        testQuestion tq = new testQuestion();
            //        tq.questionId = currentQuestionId;
            //        tq.testId = testId;
            //        tq.marks = fairquestionmarks[i];

            //        db.testQuestions.Add(tq);
            //        db.SaveChanges();
            //    }
            //    else
            //    {
            //        duplicateQuestions.Add(currentQuestionId.ToString());
            //    }
            //}
            //var returnquestion = "";
            //foreach (var questionId in duplicateQuestions)
            //{
            //    returnquestion += questionId + ",";
            //}



            //db.testQuestionDatabanks.Add(DB);
            //db.SaveChanges();

            //save the data to test table as well
            ViewBag.questionClass = ng.getStudentClass();
            ViewBag.sSubject = ng.getSubjects();
            ViewBag.ttest = ng.getActivetest();
            //string message = "Question " + returnquestion + " is already included in the test.";
            //if (returnquestion != "")
            //{
            //    return Content("<script language='javascript' type='text/javascript'>alert('" + message + "');</script>");
            //}
            return View();
        }
    }

    // Create a data model to represent the selected question data
    public class SelectedQuestionData
    {
        
        public int QuestionId { get; set; }
        public int Marks { get; set; }
    }

    public class QuestionEntity
    {
        public int QuestionId { get; set; }
        public int Marks { get; set; }
        // Add other properties for the database table
    }

}   

Controllers/studTestController.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using static System.Net.Mime.MediaTypeNames;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Rotativa;
using Rotativa.Options;
using System.IO;
using iTextSharp.text.html.simpleparser;
using System.Net;
using System.Net.Mail;



namespace NMDCATEtestPreparatory.Controllers
{

    public class studTestController : Controller
    {

        // public static long studentid = Convert.ToInt64(Session["studentid"].ToString());
        // public static long testid = 1;

        private nMDCATPrepTestEntities db = new nMDCATPrepTestEntities();
        private EmailService emailService = new EmailService();

        public studTestController()
        {
            db.Configuration.ProxyCreationEnabled = false;
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult testQuestion()
        {
            var studentid = Convert.ToInt64(Session["studentid"].ToString());
            var testId = Convert.ToInt32(Session["testid"].ToString());
            ViewBag.studentid = studentid;
            ViewBag.testId =testId;
            var teststatus = db.studentRegisterForTests.Where(x => x.studentId == studentid && x.testId == testId&& x.status=="Submitted").FirstOrDefault();
            if (teststatus != null)
            {
                return Redirect("resultview");
            }
                return View();
        }


        [HttpGet]
        public ActionResult allQuestions()
        {
            var result = db.testQuestionDatabanks.Select(x => x.questionId).ToList();

            if (result.Count() > 0)
            {
                return Json(result, JsonRequestBehavior.AllowGet);

            }
            else
            {
                return Json("end", JsonRequestBehavior.AllowGet);

            }
        }




        [HttpGet]

        public ActionResult loadFirstQuestion()
        {
            long studID = Convert.ToInt64(Session["studentid"].ToString());
            long testID = Convert.ToInt32(Session["testid"].ToString());

            try
            {
                //var result = db.testQuestionDatabanks.FirstOrDefault();
                //var allQid = db.testQuestionDatabanks.Select(x => x.questionId).Where(x.).ToList();

                var studentid = Convert.ToInt64(Session["studentid"].ToString());
                var onlyQuestion = (from st in db.studentRegisterForTests
                                    join tq in db.testQuestions on st.testId equals tq.testId
                                    join td in db.testQuestionDatabanks on tq.questionId equals td.questionId
                                    where (tq.testId == testID && st.studentId == studentid)
                                    select new
                                    {
                                        qid = td.questionId,
                                        title = td.questionTitle,
                                        markChoices = td.correctChoice,
                                        cA = td.choiceA,
                                        cB = td.choiceB,
                                        cC = td.choiceC,
                                        cD = td.choiceD,
                                    }).ToList();
                var allQid = onlyQuestion.Select(x => x.qid).ToList();
                var firstQ = allQid.FirstOrDefault();

                if (onlyQuestion != null)
                {
                    return Json(new { onlyQuestion, allQid }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { data = "Error" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception)
            {
                return Json("end", JsonRequestBehavior.AllowGet);
            }
        }



        [HttpPost]
        public ActionResult questionById(int? qid, string radioChoice, int nextQ)
        {
            int t = Convert.ToInt32(Session["testid"].ToString());
            var studentid = Convert.ToInt64(Session["studentid"].ToString());

            #region Question Save/Update
            var studAlreadyRec = db.studentAppearTests.Where(x => x.testId == t && x.studentId == studentid && x.questionId == qid).FirstOrDefault();
            if (studAlreadyRec != null)
            {

                studAlreadyRec.testId = Convert.ToInt32(Session["testid"].ToString());
                studAlreadyRec.studentId = studentid;
                studAlreadyRec.questionId = qid;
                studAlreadyRec.correctChoice = radioChoice;

                db.SaveChanges();


            }
            else
            {

                if (radioChoice != "")
                {
                    //save
                    studentAppearTest student = new studentAppearTest();
                    student.testId = Convert.ToInt32(Session["testid"].ToString());
                    student.studentId = studentid;
                    student.questionId = qid;
                    student.correctChoice = radioChoice;

                    db.studentAppearTests.Add(student);
                    db.SaveChanges();

                }
            }
            #endregion

            #region load new Question

            var onlyQuestion = (from td in db.testQuestionDatabanks
                                join sd in db.studentAppearTests on td.questionId equals sd.questionId
                                where (sd.questionId == nextQ && sd.testId == t && sd.studentId == studentid)
                                select new
                                {
                                    qid = td.questionId,
                                    title = td.questionTitle,
                                    markChoices = sd.correctChoice,
                                    cA = td.choiceA,
                                    cB = td.choiceB,
                                    cC = td.choiceC,
                                    cD = td.choiceD,
                                }).FirstOrDefault();

            if (onlyQuestion != null)
            {
                return Json(new { data = onlyQuestion }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                onlyQuestion = (from td in db.testQuestionDatabanks
                                where (td.questionId == nextQ)
                                select new
                                {
                                    qid = td.questionId,
                                    title = td.questionTitle,
                                    markChoices = "",
                                    cA = td.choiceA,
                                    cB = td.choiceB,
                                    cC = td.choiceC,
                                    cD = td.choiceD,
                                }).FirstOrDefault();
                return Json(new { data = onlyQuestion }, JsonRequestBehavior.AllowGet);
            }

            #endregion
        }


        [HttpGet]
        public ActionResult questionDropdown(int? qid, int nextQ)
        {
            var DropData = db.testQuestionDatabanks.Where(x => x.questionId == qid).FirstOrDefault();
            var studentid = Convert.ToInt64(Session["studentid"].ToString());

            int t = Convert.ToInt32(Session["testid"].ToString());

            var DropDownQues = (from td in db.testQuestionDatabanks
                                join sd in db.studentAppearTests on td.questionId equals sd.questionId
                                where (sd.questionId == nextQ && sd.testId == t && sd.studentId == studentid)
                                select new
                                {
                                    qid = td.questionId,
                                    title = td.questionTitle,
                                    markChoices = sd.correctChoice,
                                    cA = td.choiceA,
                                    cB = td.choiceB,
                                    cC = td.choiceC,
                                    cD = td.choiceD,
                                }).FirstOrDefault();

            if (DropDownQues != null)
            {
                return Json(new { data = DropDownQues }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                DropDownQues = (from td in db.testQuestionDatabanks
                                where (td.questionId == nextQ)
                                select new
                                {
                                    qid = td.questionId,
                                    title = td.questionTitle,
                                    markChoices = "",
                                    cA = td.choiceA,
                                    cB = td.choiceB,
                                    cC = td.choiceC,
                                    cD = td.choiceD,
                                }).FirstOrDefault();

                return Json(new { data = DropDownQues }, JsonRequestBehavior.AllowGet);
            }
        }


        [HttpGet]
        public ActionResult questionSkip(int qid)
        {
            var QuesData = db.testQuestionDatabanks.Where(x => x.questionId == qid).FirstOrDefault();

            if (QuesData != null)
            {
                return Json(new
                {
                    allQuestion = QuesData,
                }, JsonRequestBehavior.AllowGet);

            }
            else
            {
                return Json("end", JsonRequestBehavior.AllowGet);

            }
        }


        [HttpGet]
        public ActionResult resultview()
        {

            var studentid = Convert.ToInt64(Session["studentid"].ToString());

Controllers/testController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;


namespace NMDCATEtestPreparatory.Controllers
{
    public class testController : Controller
    {
        private nMDCATPrepTestEntities db = new nMDCATPrepTestEntities();
        // GET: student
        public ActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "User")]
        [HttpPost]
        public ActionResult Index(string testTitle, string startTime, string  endTime, string testConductionDate, int graceTime )
        {

            test tst = new test();
            tst.testTitle = testTitle;
            tst.startTime = startTime;
            CultureInfo culture = new CultureInfo("ur-PK");
            DateTime testConductionDateTime = DateTime.ParseExact(testConductionDate, "dd/MM/yyyy", culture );
            tst.testConductionDate = testConductionDateTime;
            tst.endTime = endTime;
            tst.graceTime = graceTime;
            db.tests.Add(tst);
           
            db.SaveChanges();
            return View("Index");

        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/img/favicon.png">
    <title>Quiz Master</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/select2.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/style.css">
    <link href="../../dist/css/style.min.css" rel="stylesheet">

    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <!--[if lt IE 9]>
        <script src="assets/js/html5shiv.min.js"></script>
        <script src="assets/js/respond.min.js"></script>
    <![endif]-->
    <style>
        .page-wrapper {
            display:block!important;
        }
    </style>
</head>

<body>

    <script>
        var testQuestions = [];
        var indexTestQuestion = 0;
        var size = 0;
    </script>


    <div class="main-wrapper">
        <div class="header">
            <!-- Header start -->
            <div class="header-left">
                <a href="Index.cshtml" class="logo">
                    <img src="~/assets/img/logo.png" width="40" height="40" alt="">
                    <span class="text-uppercase">Quiz Master</span>
                </a>
            </div>
            <div class="page-title-box float-left">
                <h3 class="text-uppercase">Quiz Master</h3>
            </div>

            <ul class="nav user-menu float-right">


                <li class="nav-item dropdown has-arrow">

                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="profile.html">My Profile</a>
                        <a class="dropdown-item" href="edit-profile.html">Edit Profile</a>
                        <a class="dropdown-item" href="settings.html">Settings</a>
                        <a class="dropdown-item" href="login.html">Logout</a>
                    </div>
                </li>
            </ul>
        </div>
        <div class="sidebar" id="sidebar">
            <!-- sidebar -->
            <div class="sidebar-inner slimscroll">
                <div id="sidebar-menu" class="sidebar-menu">
                    <ul>
                        @if (Session["LoginRole"].ToString() != "student")
                        {
                            <li class="menu-title">Main</li>
                            <li class="submenu">
                                <a href="#"><i class="fa fa-user" aria-hidden="true"></i> <span> Teachers</span> <span class="menu-arrow"></span></a>
                                <ul class="list-unstyled" style="display: none;">
                                    <li><a href="@Url.Action("Employee", "Home")">Add Teacher</a></li>
                                    <li><a href="@Url.Action("EmployeeList", "Home")">All Teacher</a></li>
                                    <li><a href="@Url.Action("PasswordReset", "user")">Password Change</a></li>
                                </ul>
                            </li>
                        }
                        <li class="submenu">
                            <a href="#"><i class="fa fa-user" aria-hidden="true"></i> <span> Students</span> <span class="menu-arrow"></span></a>
                            <ul class="list-unstyled" style="display: none;">
                                @if (Session["LoginRole"].ToString() != "student")
                                {
                                    <li><a href="@Url.Action("Index", "student")">Registration</a></li>
                                    <li><a href="@Url.Action("StudentList", "student")">All Students</a></li>
                                }
                                <li><a href="~/studTest/resultview">Result</a></li>

                            </ul>
                        </li>
                        @if (Session["LoginRole"].ToString() != "student")
                        {
                            <li class="submenu">
                                <a href="#"><i class="fa fa-user" aria-hidden="true"></i> <span> Test</span> <span class="menu-arrow"></span></a>
                                <ul class="list-unstyled" style="display: none;">
                                    @*<li><a href="@Url.Action("testQuestion", "studTest")">Test Created</a></li>*@
                                    <li><a href="@Url.Action("Index", "test")">Test Creation</a></li>

                                    <li><a href="@Url.Action("Index", "assignQuestionToTest")">Add Question to Test</a></li>
                                </ul>
                            </li>
                            <li class="dropdown-submenu">
                                <a href="#"><i class="fa fa-user" aria-hidden="true"></i> <span> TestQDataBank</span> <span class="menu-arrow"></span></a>

                                <ul class="list-unstyled" style="display: none;">
                                    <li> <a href="@Url.Action("Index", "testQuestionDatabanks")">MCQS</a></li>
                                    @*<li> <a href="@Url.Action("fillBlanks", "testQuestionDatabanks")">FillBlanks</a></li>
                    <li> <a href="@Url.Action("trueFalse", "testQuestionDatabanks")">TrueFalse</a></li>*@
                                </ul>
                            </li>
                            <li class="submenu">
                                <a href="javascript:void(0);"><i class="fa fa-share-alt" aria-hidden="true"></i> <span>Subjects</span> <span class="menu-arrow"></span></a>
                                <ul style="display: none;">
                                    <li>
                                        <a href="@Url.Action("Subject", "Home")"> add Subject</a>
                                        <a href="@Url.Action("subjectList", "Home")"> Subject List </a>
                                    </li>
                                </ul>
                            </li>

                        }



                    </ul>
                </div>
            </div>
        </div>
        <div class="page-wrapper">
            <div class="content container-fluid">
              
                @RenderBody()
                 
            </div>
        </div>
    </div>
    <div class="sidebar-overlay" data-reff=""></div>


    <script type="text/javascript" src="~/assets/js/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="~/assets/js/popper.min.js"></script>
    <script type="text/javascript" src="~/assets/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/assets/js/jquery.slimscroll.js"></script>
    <script type="text/javascript" src="~/assets/js/select2.min.js"></script>
    <script type="text/javascript" src="~/assets/js/moment.min.js"></script>
    <script type="text/javascript" src="~/assets/js/bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript" src="~/assets/js/app.js"></script>

    @RenderSection("Scripts", false)
</body>

</html>