Controllers/EmailSetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NMDCATEtestPreparatory.Models;
using System.Net;
using System.Net.Mail;

namespace NMDCATEtestPreparatory.Controllers
{
    public class EmailSetupController : Controller
    {
        private nMDCATPrepTestEntities db = new nMDCATPrepTestEntities();
        // GET: EmailSetup
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [Obsolete]
        public ActionResult Index(NMDCATEtestPreparatory.Models.gmail model)
        {
            SendMail("Student", model.To);
            return View();
        }

        private void SendMail(string v, string to)
        {
            throw new NotImplementedException();
        }
        #region Email
        [Obsolete]
        public void SendMail(string email, string studentName, string userName, string password)
        {

            String mail = "<!DOCTYPE html>\n" +
                "<html lang=\"en\">\n" +
                "  <head>\n" +
                "    <meta charset=\"UTF-8\" />\n" +
                "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n" +
                "    <title>Your Website - Contact Us</title>\n" +
                "    <style>\n" +
                "      /* Add your CSS styles here */\n" +
                "      * {\n" +
                "        box-sizing: border-box;\n" +
                "      }\n" +
                "      body {\n" +
                "        font-family: Arial, Helvetica, sans-serif;\n" +
                "        margin: 0;\n" +
                "        padding: 0;\n" +
                "      }\n" +
                "      .container {\n" +
                "        max-width: 600px;\n" +
                "        margin: 0 auto;\n" +
                "        background-color: #ffffff;\n" +
                "        border-radius: 10px;\n" +
                "        overflow: hidden;\n" +
                "        box-shadow: 0px 0px 15px 0px rgba(0, 0, 0, 0.1);\n" +
                "      }\n" +
                "      .header {\n" +
                "        background-color: #f5f5f5;\n" +
                "        padding: 20px;\n" +
                "        text-align: center;\n" +
                "      }\n" +
                "      .header h1 {\n" +
                "        font-size: 32px;\n" +
                "        margin: 0;\n" +
                "      }\n" +
                "      .main {\n" +
                "        padding: 20px;\n" +
                "      }\n" +
                "      .main p {\n" +
                "        font-size: 16px;\n" +
                "        line-height: 1.5;\n" +
                "        margin-bottom: 20px;\n" +
                "      }\n" +
                "      .main a {\n" +
                "        background-color: #00bfff;\n" +
                "        border-radius: 5px;\n" +
                "        color: #ffffff;\n" +
                "        display: inline-block;\n" +
                "        font-size: 18px;\n" +
                "        padding: 10px 20px;\n" +
                "        text-decoration: none;\n" +
                "      }\n" +
                "      .main a:hover {\n" +
                "        background-color: #0080ff;\n" +
                "      }\n" +
                "      .footer {\n" +
                "        background-color: #f5f5f5;\n" +
                "        color: #999999;\n" +
                "        font-size: 14px;\n" +
                "        padding: 20px;\n" +
                "        text-align: center;\n" +
                "      }\n" +
                "    </style>\n" +
                "  </head>\n" +
                "  <body>\n" +
                "    <div class=\"container\">\n" +
               "<div class=\"header\">\n" +
             "  <h1>Contact Us</h1>\n" +
             "</div>\n" +
             "<div class=\"main\">\n" +
             "  <p>Dear " + studentName + ",</p>\n" +
             "  <p>Your UserName : " + userName + "</p>\n" +
             "  <p>Your Password : " + password + "</p>\n" +
             "  <p>Thank you for contacting us. We have received your inquiry and will do our best to assist you as soon as possible.</p>\n" +
             "  <p>If you have any further questions, please do not hesitate to contact us by +923069881188</p>\n" +
             //"  <p><a href=\"#\">Contact Us</a></p>\n" +
             "</div>\n" +
             "<div class=\"footer\">\n" +
             "  <p>This email was sent to you from Your Website. To unsubscribe from our emails, please click <a href=\"#\">here</a>.</p>\n" +
             "</div>\n" +
             "</div>\n" +
             "</body>\n" +
             "</html>";
            //from,to,subject,body
            MailMessage mymail = new MailMessage("knain9292@gmail.com", email, "Quiz Master", mail);
            mymail.IsBodyHtml = true;
            string EmailProvider = "smtp.gmail.com";
            var client = new SmtpClient(EmailProvider, 587)
            {
                Credentials = new NetworkCredential("knain9292@gmail.com", "dcsglanqyeefkpun"),
                EnableSsl = true,
            };
            try
            {
                //client.UseDefaultCredentials = true;
                client.Send(mymail);
                TempData["msg"] = "send";
            }
            catch (Exception ex)
            {
                Response.Write(ex);
                TempData["msg"] = ex.Message.ToString();
            }
        }

        #endregion
    }
}

Views/EmailSetup/Index.cshtml
@model NMDCATEtestPreparatory.Models.gmail
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/img/favicon.png">
    <title>NMDCAT</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/select2.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/style.css">
    <link href="../../dist/css/style.min.css" rel="stylesheet">

    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <!--[if lt IE 9]>
        <script src="assets/js/html5shiv.min.js"></script>
        <script src="assets/js/respond.min.js"></script>
    <![endif]-->
    <style>
        .page-wrapper {
            display: block !important;
        }
    </style>
</head>
<body>
    <div>
        @using (Html.BeginForm("Index", "EmailSetup", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <table border="0" cellpadding="0" cellspacing="0">
                <tr>
                    <td style="width: 80px">
                        To:
                    </td>
                    <td>
                        @Html.TextBoxFor(model => model.To)
                    </td>
                </tr>
                <tr>
                    <td>
                        Subject:
                    </td>
                    <td>
                        @Html.TextBoxFor(model => model.Subject)
                    </td>
                </tr>
                <tr>
                    <td valign="top">
                        Body:
                    </td>
                    <td>
                        @Html.TextAreaFor(model => model.Body, new { rows = "3", cols = "20" })
                    </td>
                </tr>
                <td></td>
                <td>
                    <input type="submit" value="Send" />
                </td>



            </table>
            <span style="color:green">@ViewBag.Message</span>
        }
    </div>

    <div class="sidebar-overlay" data-reff=""></div>


    <script type="text/javascript" src="~/assets/js/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="~/assets/js/popper.min.js"></script>
    <script type="text/javascript" src="~/assets/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/assets/js/jquery.slimscroll.js"></script>
    <script type="text/javascript" src="~/assets/js/select2.min.js"></script>
    <script type="text/javascript" src="~/assets/js/moment.min.js"></script>
    <script type="text/javascript" src="~/assets/js/bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript" src="~/assets/js/app.js"></script>

  
</body>
</html>