Controllers/studentController.cs
using NMDCATEtestPreparatory.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Net.Mail;

namespace NMDCATEtestPreparatory.Controllers
{
    public class studentController : Controller
    {
        private nMDCATPrepTestEntities db = new nMDCATPrepTestEntities();
        private nmdcatGeneral ng = new nmdcatGeneral();
        private EmailService emailService = new EmailService();
        // GET: student
        [Authorize(Roles = "User")]
        [HttpGet]

        public ActionResult Index()
        {
            List<universityRanking> rankingu = db.universityRankings.ToList();
            ViewBag.universityRankings = rankingu.Select(x => new SelectListItem { Value = x.universityRankingId.ToString(), Text = x.universityName });

            List<departmentRanking> rankingd = db.departmentRankings.ToList();
            ViewBag.departmentRankings = rankingd.Select(x => new SelectListItem { Value = x.departmentRankingId.ToString(), Text = x.departmentName });

            ViewBag.ttest = ng.getActivetest();
            return View();
        }
        [Authorize(Roles = "User")]
        [HttpPost]
        public ActionResult Index( int? studentId,string studentName, string studentFName, 
            string email, string contact, string DOB, string userName, string password,
            string gender, int? ttest, string testStatus, HttpPostedFileBase img , string departmentRankings)
            {
    //        DateTime dtDOB = Convert.ToDateTime(DOB);
            DateTime dtDOB = DateTime.Parse(DOB);
            
            password = CreateRandomPassword();
            userName = GenerateName();
           


            if (studentId != null)
            {
                //search stud if already exist
                var studRec = db.students.Where(y => y.studentId == studentId).FirstOrDefault();
                if(studRec != null)
                {
                    studRec.studentName = studentName;
                    studRec.studentFName = studentFName;
                    studRec.email = email;
                    studRec.contact = contact;
                    studRec.userName = userName;
                    studRec.password = password;
                    studRec.departmentName = departmentRankings;
                    
                  studRec.DOB = Convert.ToDateTime(dtDOB, System.Globalization.CultureInfo.GetCultureInfo("ur-PK").DateTimeFormat);
                    if (gender == "Male")
                    {
                        studRec.gender = 1;
                    }
                    else if (gender == "Female")
                    {
                        studRec.gender = 2;
                    }
                    else
                    {
                        studRec.gender = 3;
                    }
                    if (img != null)
                    {
                        var fileName = Path.GetFileName(img.FileName);
                        var timestamp = DateTime.Now.ToString("ddMMyyyyHHmmss");
                        var uniqueFilename = $"{timestamp}_{fileName}";
                        var path = Path.Combine(Server.MapPath("~/MyImages"), uniqueFilename);
                        img.SaveAs(path);
                        studRec.studentPicture = uniqueFilename;
                    }
                    

                // studentRegisterForTest studRegForTest = new studentRegisterForTest();
                var studRegForTest = db.studentRegisterForTests.Where(x => x.studentId == studentId).FirstOrDefault();
                    if (studRegForTest != null)
                    {
                        studRegForTest.studentId = studRec.studentId;
                        studRegForTest.testId = ttest;
                        studRegForTest.userName = studRec.userName;
                        studRegForTest.password = studRec.password;
                        studRegForTest.testStatus = Convert.ToBoolean(testStatus);
                        studRegForTest.status = "Not submitted";
                        //db.studentRegisterForTests.Add(studRegForTest);

                        db.SaveChanges();
                    }
                }
              
            }
            else
            {
                
                student std = new student();
                //var ttt = (from td in db.students
                //           join sd in db.studentRegisterForTests on td.studentId equals sd.studentId
                //           where (sd.userName == userName && sd.password == password)
                //           select new
                //           {
                //               userr = td.userName,
                //               pass = td.password,
                //           }).FirstOrDefault();

                password = CreateRandomPassword();
                userName = GenerateName();
                std.studentName = studentName;
                std.studentFName = studentFName;
                std.email = email;
                std.contact = contact;
                std.userName = userName;
                std.password = password;
                std.departmentName = departmentRankings;
              
                std.studentId = Convert.ToInt32(studentId);
                std.DOB = Convert.ToDateTime(DOB, System.Globalization.CultureInfo.GetCultureInfo("ur-PK").DateTimeFormat);
                if (gender == "Male")
                {
                    std.gender = 1;
                }
                else if (gender == "Female")
                {
                    std.gender = 2;
                }
                else
                {
                    std.gender = 3;
                }
                if (img != null)
                {
                    var fileName = Path.GetFileName(img.FileName);
                    var timestamp = DateTime.Now.ToString("ddMMyyyyHHmmss");
                    var uniqueFilename = $"{timestamp}_{fileName}";
                    var path = Path.Combine(Server.MapPath("~/MyImages"), uniqueFilename);
                    img.SaveAs(path);
                    std.studentPicture = uniqueFilename;
                }

                db.students.Add(std);
                db.SaveChanges();
                studentRegisterForTest studRegForTest = new studentRegisterForTest();

                studRegForTest.studentId = std.studentId;
                studRegForTest.testId = ttest;
                studRegForTest.userName = std.userName;
                studRegForTest.password =std.password;
                studRegForTest.testStatus = Convert.ToBoolean(testStatus);
                studRegForTest.status = "Not submitted";
                db.studentRegisterForTests.Add(studRegForTest);
                db.SaveChanges();
            }

            var emailSetupController = new EmailSetupController();
            //from , to, subj, body 
            emailSetupController.SendMail(email,studentName, userName, password);

            return Redirect("Index");

        }
        //private void SendMail(string studentName, string email, string userName, string password)
        // {
        //     throw new NotImplementedException();
        // }

        private static string CreateRandomPassword(int length = 5)
        {
           
            string validChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*?_-";
            Random random = new Random();

            char[] chars = new char[length];
            for (int i = 0; i < length; i++)
            {
                chars[i] = validChars[random.Next(0, validChars.Length)];
            }
            return new string(chars);
        }

        public static string GenerateName(int L = 8)
        {
            //Random r = new Random();
            //string[] consonants = { "A", "C", "D", "f", "g", "h", "j", "k", "l", "m", "l", "n", "p", "q", "r", "s", "s", "z", "t", "v", "w", "x" };
            //string[] vowels = { "a", "e", "I", "O", "U", "A", "Y" };
            //string Name = "";
            //Name += consonants[r.Next(consonants.Length)].ToUpper();
            //Name += vowels[r.Next(vowels.Length)];
            //int b = 0; 
            //while (b < L)
            //{
            //    Name += consonants[r.Next(consonants.Length)];
            //    b++;
            //    Name += vowels[r.Next(vowels.Length)];
            //    b++;
            //}

            //return Name;

            string validChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
            Random random = new Random();

            char[] chars = new char[L];
            for (int i = 0; i < L; i++)
            {
                chars[i] = validChars[random.Next(0, validChars.Length)];
            }
            return new string(chars);

        }
        [Authorize(Roles = "User")]
        [HttpGet]
        public JsonResult searchByContact(string searchby)
        {
            var studRec = (from s in db.students
                           where (s.contact == searchby)
                           select new
                           {
                               studentName = s.studentName,
                               studentFName=s.studentFName,
                               gender=s.gender,
                               email=s.email,
                               DOB=s.DOB,
                               userName= s.userName,
                               password=s.password,
                               contact= s.contact,
                               studentId= s.studentId
                           }).FirstOrDefault();
            if (studRec != null)
            {
                return Json(new { data = studRec }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { data = "" }, JsonRequestBehavior.AllowGet);
            }

        }

Views/student/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-header">
    <div class="row">
        <div class="col-lg-7 col-md-12 col-sm-12 col-12">
            <h5 class="text-uppercase">Student Regestration Form</h5>
        </div>
        @*<div class="col-lg-5 col-md-12 col-sm-12 col-12">
            <ul class="list-inline breadcrumb float-right">
                <li class="list-inline-item"><a href="index.html">Home</a></li>
                <li class="list-inline-item"><a href="index.html">Student</a></li>
                <li class="list-inline-item"> add student</li>
            </ul>
        </div>*@
    </div>
</div>

<div class="page-content">

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="card">
                <div class="page-title">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                            <div class="page-title">Basic information</div>
                        </div>

                    </div>

                </div>
                <div class="card-body">
                    <form action="~/student/Index" method="post" enctype="multipart/form-data">



                        <div class=" row">

                            <input type="hidden" name="studentId" id="studentId" />

                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="form-group custom-mt-form-group">
                                <input type="text" name="searchbycontact" id="searchbycontact" onblur="funsuggestion()" />
                                <label class="control-label">Search By Contact</label><i class="bar"></i>
                            </div>
                        </div>
                        <div class="form-group custom-mt-form-group">
                            <input type="file" name="img" id="studentPicture" accept="image/*" />
                            <label class="control-label">Student Picture</label><i class="bar"></i>
                        </div>

                        <div class="row">

                            <div class="col-lg-6 col-md-6 col-sm-6 col-12">

                                <div class="form-group custom-mt-form-group">
                                    <input type="text" name="studentName" id="studentName" />
                                    <label class="control-label">Student Name</label><i class="bar"></i>
                                </div>
                                <div class="form-group custom-mt-form-group">
                                    <input type="text" name="studentFName" id="studentFName" />
                                    <label class="control-label">Father Name</label><i class="bar"></i>
                                </div>
                                <div class="form-group custom-mt-form-group">
                                    <input class="datetimepicker" type="text" name="DOB" id="DOB">
                                    <label class="control-label">Birth Date</label><i class="bar"></i>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="form-group custom-mt-form-group">
                                    <input type="text" name="email" id="email" />
                                    <label class="control-label">Email</label><i class="bar"></i>
                                </div>
                                <div class="form-group custom-mt-form-group">
                                    <input type="text" name="Contact" id="Contact" />
                                    <label class="control-label">Contact</label><i class="bar"></i>
                                </div>
                                <div class="form-group custom-mt-form-group">
                                    <select name="gender" id="gender">
                                        <option>Male</option>
                                        <option>Female</option>
                                        <option>Other</option>
                                    </select>
                                    <label class="control-label">Gender</label><i class="bar"></i>
                                </div>
                                <div class="form-group custom-mt-form-group">
                                    @*<input type="text" id="testStatus" name="testStatus" oninput="validateBinaryInput(this)" maxlength="1" />*@
                                    <select id="testStatusSelect " name="testStatus" onchange="updateTestStatus()">
                                        <option value="true">True</option>
                                        <option value="false">False</option>
                                    </select>
                                    <label class="control-label">Test Status</label><i class="bar"></i>
                                </div>

                                <div class="form-group custom-mt-form-group">
                                    <input type="hidden" name="userName" id="userName" />
                                    @* <label class="control-label">User Name</label><i class="bar"></i>*@
                                </div>

                                <div class="form-group custom-mt-form-group">
                                    <input type="hidden" name="password" id="password" />
                                    @*  <label class="control-label">Password </label><i class="bar"></i>*@
                                </div>
                            </div>
                        </div>
                        @*<div class="form-group custom-mt-form-group">

                            <label class="control-label">Select University</label><i class="bar"></i>
                           
                            @Html.DropDownList("universityRankings", null, new { @class = "form-control", required = true })

                        </div>*@
                        <div class="form-group custom-mt-form-group">
                            
                            <label class="control-label">Select Department</label><i class="bar"></i>
                            @Html.DropDownList("departmentRankings", null, new { @class = "form-control", required = true })

                        </div>
                        <div class="col-sm-6 col-md-3">
                            <div class="form-group custom-mt-form-group">
                                @Html.DropDownList("ttest")
                                <label class="control-label">Add To Test</label><i class="bar"></i>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="form-group custom-mt-form-group">
                                    <button type="submit" class="btn btn-success btn-block mt-4 mb-2" value="Save" id="save"> Save </button>
                                </div>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<script>

        function funsuggestion() {
            var searchby = $("#searchbycontact").val();
        $.ajax({
                        type: "Get",
                        url: '@Url.Action("searchByContact", "student")',
                        contentType: "application/json; charset=utf-8",
            data: { searchby: searchby},
                        datatype: "json",
                        success: function (data) {
                            console.log(data);
                            if (data.data != "") {
                                $("#studentName").val(data.data.studentName);
                                $("#studentFName").val(data.data.studentFName);

                                if (data.data.gender == 1) {
                                    $("#gender").val("Male");
                                }
                                else  {
                                    $("#gender").val("Female");

                                }

                                $("#DOB").val(getDateFormatted(data.data.DOB));
                                $("#email").val(data.data.email);
                                $("#Contact").val(data.data.contact);
                                $("#studentId").val(data.data.studentId);


                            }

                        },
                        error: function () {
                            alert("Error Orrured In server");
                        }
                    });
        }
        function getDateFormatted(date) {
            debugger;
            var pattern = /Date\(([^)]+)\)/;
            var results = pattern.exec(date);
            var dt = new Date(parseFloat(results[1]));
            debugger;

            var gdate = dt.getDate();


            var month = (dt.getMonth() + 1);

            return (month) + "/" + gdate + "/" + dt.getFullYear();
        }
</script>

@*<script>
        function validateBinaryInput(input) {
            var binaryRegex = /^[01]$/; // Regular expression for matching 0 or 1
            var inputValue = input.value;

            if (!binaryRegex.test(inputValue)) {
                // If the input value does not match the binaryRegex, clear the input field
                input.value = '';
            }
        }
    </script>*@
<script>
    function updateTestStatus() {
        const testStatusSelect = document.getElementById('testStatusSelect');
        const testStatus = testStatusSelect.value; // Get the selected value

        // Perform your desired logic with the testStatus value here
        // For example, you can display the current status:
        const testStatusDisplay = document.getElementById('testStatusDisplay');
        testStatusDisplay.textContent = `Test Status: ${testStatus}`;
    }
</script>

Views/student/StudentList.cshtml
@model IEnumerable<NMDCATEtestPreparatory.student>
@{

}
<div class="page-header">
    <div class="row">
        <div class="col-lg-7 col-md-12 col-sm-12 col-12">
            <h5 class="text-uppercase">All  Students List</h5>
        </div>

    </div>
</div>
<div class="row filter-row">
    <div class="col-sm-6 col-md-3 col-lg-3 col-xl-2 col-12">
        <div class="col-lg-6 col-md-6 col-sm-6 col-12">
            <div class="form-group custom-mt-form-group">
            <input type="text" name="searchbyID" id="searchID" onchange="funsuggestion()" />
            <label class="control-label">Search By ID</label><i class="bar"></i>
        </div>     <div class=" row">

                <input type="hidden" name="studentId" id="studentId" />

            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table class="table table-striped custom-table m-b-0" @*id="tbl"*@>
                <thead>
                    <tr>
                        <th class="text-center">Student ID</th>
                        <th class="text-center"> Name</th>
                        <th class="text-center"> Father Name </th>
                        <th class="text-center"> Gender</th>
                        <th class="text-center">DOB</th>
                        <th class="text-center"> Email</th>
                        <th class="text-center"> Contact</th>
                        <th class="text-center" >Student Picture</th>


                    </tr>
                </thead>
                <tbody id="datalist">
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            <strong>@item.studentId</strong>
                        </td>
                        <td>@item.studentName</td>
                        <td>@item.studentFName</td>
                        <td>@item.gender</td>
                        <td>@item.DOB</td>
                        <td>@item.email</td>
                        <td>@item.contact </td>
                        <td><img src="~/MyImages/@item.studentPicture" style="width:30%" /></td>
                        @*<td>
            <a href="~/student/studentEdit1?id=@item.studentId">Edit</a>

        </td>*@

                    </tr>
                    }


                </tbody>
            </table>
        </div>
    </div>
</div>


<script>
     function funsuggestion() {

        var searchby = $("#searchID").val();
        alert(searchby);
        $.ajax({
                        type: "Get",
                        url: '@Url.Action("searchByID", "student")',
                        contentType: "application/json; charset=utf-8",
            data: { searchby: searchby},
                        datatype: "json",
                        success: function (data) {
                            console.log(data);
                            var dd = '';
                            if (data.data != "") {
                                dd+='<tr>'
                                dd += '<td>' + data.data.studentId+'</td>'
                                dd += '<td>' + data.data.studentName + '</td>'
                                dd += '<td>' + data.data.studentFName + '</td>'
                                dd += '<td>' + data.data.gender +'</td>'
                                dd += '<td>' + data.data.DOB+'</td>'
                                dd += '<td>' + data.data.email+'</td>'
                                dd += '<td>' + data.data.contact + '</td>'
                                dd += '<td><img src="/MyImages/' + data.data.studentPicture + '" alt="Student Image"></td>'
                                dd+='<td></td></tr>'




                                //$("#DOB").val(getDateFormatted(data.data.DOB));
                                //$("#Email").val(data.data.Email);
                                //$("#Contact").val(data.data.Contact);



                            }
                            $("#datalist").html(dd);

                        },
                        error: function () {
                            alert("Error Orrured In server");
                        }
                    });
    }
    function getDateFormatted(date) {
        debugger;
        var pattern = /Date\(([^)]+)\)/;
        var results = pattern.exec(date);
        var dt = new Date(parseFloat(results[1]));
        debugger;

        var gdate = dt.getDate();


        var month = (dt.getMonth() + 1);

        return (month) + "/" + gdate + "/" + dt.getFullYear();
    }

</script>

Views/student/studentEdit1.cshtml
@model NMDCATEtestPreparatory.student

@{
    ViewBag.Title = "studentEdit1";
}

<div class="page-header">
    <div class="row">
        <div class="col-lg-7 col-md-12 col-sm-12 col-12">
            <h5 class="text-uppercase">Student Regestration Form</h5>
        </div>
        <div class="col-lg-5 col-md-12 col-sm-12 col-12">
            <ul class="list-inline breadcrumb float-right">
                <li class="list-inline-item"><a href="index.html">Home</a></li>
                <li class="list-inline-item"><a href="index.html">Student</a></li>
                <li class="list-inline-item"> add student</li>
            </ul>
        </div>
    </div>
</div>

<div class="page-content">

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="card">
                <div class="page-title">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                            <div class="page-title">Basic information</div>
                        </div>

                    </div>

                </div>
                <div class="card-body">
                    <form action="~/student/studentEdit1" method="post" enctype="multipart/form-data">



                        <div class=" row">

                            <input type="hidden" name="studentId" id="studentId" />

                        </div>
                        @*<div class="col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="form-group custom-mt-form-group">
                                <input type="text" name="searchbycontact" id="searchbycontact" onblur="funsuggestion()" />
                                <label class="control-label">Search By Contact</label><i class="bar"></i>
                            </div>
                        </div>*@
                        <div class="form-group custom-mt-form-group">
                            <input type="file" name="img" id="studentPicture" accept="image/*" />
                            <label class="control-label">Student Picture</label><i class="bar"></i>
                        </div>

                        <div class="row">

                            <div class="col-lg-6 col-md-6 col-sm-6 col-12">

                                <div class="form-group custom-mt-form-group">
                                    <input type="text" name="studentName" id="studentName" value="@Model.studentName"/>
                                    <label class="control-label">Student Name</label><i class="bar"></i>
                                </div>
                                <div class="form-group custom-mt-form-group">
                                    <input type="text" name="studentFName" id="studentFName" value="@Model.studentFName"/>
                                    <label class="control-label">Father Name</label><i class="bar"></i>
                                </div>
                                <div class="form-group custom-mt-form-group">
                                    <input class="datetimepicker" type="text" name="DOB" id="DOB"value="@Model.DOB">
                                    <label class="control-label">Birth Date</label><i class="bar"></i>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="form-group custom-mt-form-group">
                                    <input type="text" name="email" id="email" value="@Model.email"/>
                                    <label class="control-label">Email</label><i class="bar"></i>
                                </div>
                                <div class="form-group custom-mt-form-group">
                                    <input type="text" name="Contact" id="Contact"value="@Model.contact" />
                                    <label class="control-label">Contact</label><i class="bar"></i>
                                </div>
                                <div class="form-group custom-mt-form-group">
                                    <select name="gender" id="gender"value="@Model.gender">
                                        <option>Male</option>
                                        <option>Female</option>
                                        <option>Other</option>
                                    </select>
                                    <label class="control-label">Gender</label><i class="bar"></i>
                                </div>
                                <div class="form-group custom-mt-form-group">
                                    @*<input type="text" id="testStatus" name="testStatus" oninput="validateBinaryInput(this)" maxlength="1" />*@
                                    <select id="testStatusSelect " name="testStatus" onchange="updateTestStatus()">
                                        <option value="true">True</option>
                                        <option value="false">False</option>
                                    </select>
                                    <label class="control-label">Test Status</label><i class="bar"></i>
                                </div>

                                <div class="form-group custom-mt-form-group">
                                    <input type="hidden" name="userName" id="userName" />
                                    @* <label class="control-label">User Name</label><i class="bar"></i>*@
                                </div>

                                <div class="form-group custom-mt-form-group">
                                    <input type="hidden" name="password" id="password" />
                                    @*  <label class="control-label">Password </label><i class="bar"></i>*@
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-6 col-md-3">
                            @*<div class="form-group custom-mt-form-group">
                                @Html.DropDownList("ttest")
                                <label class="control-label">Add To Test</label><i class="bar"></i>
                            </div>*@
                            <div class="col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="form-group custom-mt-form-group">
                                    <button type="submit" class="btn btn-success btn-block mt-4 mb-2" value="Save" id="save"> Save </button>
                                </div>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>